server:
  port: 8016
spring:
  application:
    name: zuulServer
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8010/eureka/
  instance:
    prefer-ip-address: true
zuul:
  routes:
    loginmodule: /login-service/**
    menumodule: /menu-service/**
    orderModules: /order-service/**
    usermodule: /user-service/**