server:
  port: 8014
spring:
  application:
    name: menumodule
  datasource:
    name: orderdemo
    url: jdbc:mysql://localhost:3306/orderdemo?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8010/eureka/
  instance:
    prefer-ip-address: true
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl